### ISSUE TITLE
Draw the snake's head on the scene.

### ISSUE THREAD

**Issue by monacofj** [courselab/ttsnake#1]
Draw the snake's head on the game scene at its current position.
When completed, assign issue #4 .

**Comment by leomiassi** [comment]
Olá professor, poderia me atribuir a esse item?

**Comment by matheushjs** [comment]
Talvez eu tenha resolvido essa issue em #15?
A não ser que a cabeça tenha um design diferenciado né
help us @monacofj

**Comment by matheushjs** [comment]
Fixed by #43
