### ISSUE TITLE
Should we keep displaying more than one energy block at a time?

### ISSUE THREAD

**Issue by JayroBoy** [courselab/ttsnake#45]
I just sat down to code more energy blocks(#41), and at first it seemed like a very trivial problem: Just change the number defined as MAX_ENERGY_BLOCKS, adapt the code and call it a day. However, I quickly figured out that this would only delay the problem of blocks running out, and not solve it. Furthermore, there are some pretty famous iteractions of snake(Such as this one https://helpfulsheep.com/snake/, from nokia phones) in which there's only ever one normal energy block on screen. So it seems we have three options:
1 - Just increase the number of pre-generated energy blocks and make the game a speedrun/time trial (#35 would then be answered as "Keep it as is")
2 - Scrap the pre-generation and generate a new block every time the snake eats the current one
3 - A hybrid approach: keep the current pre-generation of 5 blocks and generate 5 new blocks when the snake eats every 5th one.

So, which one should we do? I'm leaning 2, but 3 could be fun too. Maybe in the future give players an option to play a separate game mode with 1 as the solution?

**Comment by matheushjs** [comment]
I actually like all the proposals hahaha. However, for option 1 I would still generate one block at a time, up to a fixed number of blocks (e.g. 50), so if 2 is implemented, then implementing option 1 as I am proposing here is easy.

For now **I suggest implementing option 3** with a `#define PRE_BLOCK_COUNT` set to some number, in a way that if we define it to be 1 then it reduces to the classical game (option 2).

Then later we can think of how the player can modify the game settings without tinkering with the source code, which will likely require a particular graphical (ascii) interface.

**Comment by monacofj** [comment]
Take a look at #48

**Comment by monacofj** [comment]
Closing as it may be further discussed in #48.
