### ISSUE TITLE
The game logic.

### ISSUE THREAD

**Issue by monacofj** [courselab/ttsnake#48]
I think this has to do with #45, #45, #30 and perhaps other issues, but maybe it's work to discuss the game logic in one place.

When I played Tron back in the 80's (yes, I'm old school), most implementations out there, as far as I can remember, worked more or less like this.

There is a fixed number of energy blocks randomly scattered in the sene (say 5, or 6). As soon as the snake eats a block, another one spawns elsewhere. The snake never stops and length increases as it eats. Usually, the snake speed could be modified at the game start by selecting "ease", "normal" or "hard" mode, but it remained fixed during the game session.

The game score was basically the snake length (which equals que number of blocks eaten). The key challenge posed by this game is because as the snake grows, it becomes harder and harder for it not to bite its own tail. The snake dies if touches the game boundaries or if it bites itself --- this includes reversing the movement (if the snake is moving leftwards and the user press the key to move rightward, it counts as a bite).

Finally, the snake looses energy as it moves. If a player keeps wondering and missing blocks for too long, game over.

Good skills are therefore required to keep eating blocks at a right rate, with a long snake, and not getting trapped by its tail.

Well, this is how most 80's snakes used to work, at least the ones I played in 8-bit and 16-bit PCs in the past...

**Comment by JayroBoy** [comment]
I changed the files in the feature-moreEnergyBlocks branch to always keep MAX_ENERGY_BLOCKS(currently 3) on-screen. I believe @brudel was working on updating the way the game computes score.

**Comment by Alecxannder-Sonnenberg** [comment]
I'm okay with following the logic, as defined above by @monacofj, during development and as of this moment I have nothing to add.

**Comment by brudel** [comment]
@JayroBoy In fact, I choose to work in other stuff for now.

I like the logic proposed in this issue, maybe just not the part of dying by reversing the movement.

**Comment by monacofj** [comment]
> @JayroBoy In fact, I choose to work in other stuff for now.
> 
> I like the logic proposed in this issue, maybe just not the part of dying by reversing the movement.

I agree. Perhaps reverse movement should not even be allowed by design.

**Comment by monacofj** [comment]
I guess we may consider this logic consensually agreed upon for the next release.
Closing this issue. Should anyone have further considerations, fell free to reopen it.
