### ISSUE TITLE
Interface for changing game settings

### ISSUE THREAD

**Issue by matheushjs** [courselab/ttsnake#49]
There will be multiple game modes, so we will need an interface for changing between them.

**Comment by monacofj** [comment]
How about starting with command-line options before considering an ASCII GUI?

**Comment by matheushjs** [comment]
@monacofj For now there is only one setting to configure, so a command line option would be possibly better.

But since we were possibly going towards having multiple game modes (see #41 and #48) I thought a graphical interface would be better...

For a speedrun mode, one would be able to configure the time limit. For the mode you propose in #48, there would be a choice of easy, medium or hard modes, and also the number of blocks too...

So I thought the GUI would be eventually unavoidable, but there is the risk that we won't implement all these varieties, thus rendering the GUI exaggerated...
