### ISSUE TITLE
game_delay incoherence

### ISSUE THREAD

**Issue by brudel** [courselab/ttsnake#51]
game_delay starts with 250000 but MAX_GAME_DELAY is 94000.

**Comment by Alecxannder-Sonnenberg** [comment]
This seems like an easy issue to fix but I don't know which one is better, to increase MAX_GAME_DELAY to 250000 or decrease game_delay to start with 94000. 

In my understanding the former will make the result from the player input feel slower while the latter may make the game flow to seem faster. 

If we define this we can tag this as a good first issue and let someone new to the project solve it.

**Comment by matheushjs** [comment]
Agree that this could be left as a good first issue

**Comment by matheushjs** [comment]
Taking this as we need it for version 0.1.0
