### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by brudel** [courselab/ttsnake#60]
Thereafter bootstrapping with ./autogen.sh

./configure returns error:
```./config.status: line 1299: `$as_dirname -- "$_am_arg" ||
$as_expr X"$_am_arg" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| 	 X"$_am_arg" : 'X\(//\)[^/]' \| 	 X"$_am_arg" : 'X\(//\)$' \| 	 X"$_am_arg" : 'X\(/\)' \| . 2>/dev/null ||
$as_echo X"$_am_arg" |
    sed '/^X\(.*[^/]\)\/\/*[^/][^/]*\/*$/{
	    s//\1/
	    q
	  }
	  /^X\(\/\/\)[^/].*/{
	    s//\1/
	    q
	  }
	  /^X\(\/\/\)$/{
	    s//\1/
	    q
	  }
	  /^X\(\/\).*/{
	    s//\1/
	    q
	  }
	  s/.*/./; q'`/stamp-h1: Permission denied```
But works well if executed with sudo.

Then make install returns error:
```make: *** No rule to make target 'ttsnake.sh', needed by 'ttsnake'.  Stop.```

it compiles ttsnack.bin, but don't ttsnake neither installs.

**Comment by matheushjs** [comment]
Bug introduced in #55 

@monacofj needs to `git add` the file ttsnake.sh
