### ISSUE TITLE
Choose the screen size and  vertical delimiters.

### ISSUE THREAD

**Issue by amigayatri** [courselab/ttsnake#66]
I'm thinking of adding some way to choose the screen size and maybe the vertical delimiters also, in the settings menu. What do you think about it?

**Comment by monacofj** [comment]
Edited wordings and set label "question".
If upvoted, please, change label to enhance.

**Comment by matheushjs** [comment]
I think changing screen size is a great idea.

Changing the delimiter might be more difficult than we anticipate, due to how things are implemented. If the user sets it as being the same character as an energy block or a body part of the snake, it will cause bugs, I think.

**Comment by monacofj** [comment]
Closing as it is handled in #83
