### ISSUE TITLE
Change the way the game computes score

### ISSUE THREAD

**Issue by JayroBoy** [courselab/ttsnake#71]
As discussed in #48, the current way the game computes score is probably not the best way to implement a score system. This has to be changed to make the score equal to the amount of blocks eaten, as opposed to amount of blocks eaten divided by time. Since we do want the possibility of a score of 0, we will be using the number of blocks eaten, and not the snake's length, as the scoring metric.

**Comment by monacofj** [comment]
Totally agree.
