### ISSUE TITLE
Should the snake have a limit to how much energy it can store?

### ISSUE THREAD

**Issue by JayroBoy** [courselab/ttsnake#77]
This can dramatically change how #63 is implemented, so, if we want it on release 0.1.0, this question is pretty important.

**Comment by monacofj** [comment]
Sure it's important. 
At a first glance, one might think of a pragmatical limit, implying how long the snake can linger without eating something, or  perphas what is the practical limit achienved by pro-players?

**Comment by JayroBoy** [comment]
i'm inclined to set it as NROWS+NCOLS, to ensure that there isn't an impossible situation in which the snake has max energy but can't get to any energy blocks without dying.
