### ISSUE TITLE
Game crashing at the end of animation

### ISSUE THREAD

**Issue by joao-zanutto** [courselab/ttsnake#79]
**Environment:** Ubuntu 20.10
**Terminal:** zsh

**Steps to reproduce:**
1. Download the tarball file
2. Extract it and open it's extracted folder in a terminal
3. Install the game with `./configure`, `make` and `make install`
4. Run the game with `ttsnake`
5. Wait for the initial animation to end

**Expected Result:**
> After the animation ends, the game menu should be shown

**Actual Result:**
> The game crashes after the animation ends 

**Evidences**

https://user-images.githubusercontent.com/11475695/107068680-b0f20e80-67bf-11eb-9a83-0ad0709418c4.mp4

![image](https://user-images.githubusercontent.com/11475695/107067670-602de600-67be-11eb-85f2-df02580b5068.png)

**Comment by monacofj** [comment]
Reproduction confirmed here.

Project-tree binary ok; binary installed from tarball crashes with reported error.

**Comment by matheushjs** [comment]
You need to install with

```
sudo make install
```

Unless you tell `./configure` to install the program in a local directory.

As it is, it is installing in `/usr/local`, which requires `sudo` to modify.

See the error in your terminal in the end of the video.

> /usr/bin/install: cannot create regular file '/usr/local/bin/ttsnake.bin': Permission denied

@monacofj I'm surprised you could reproduce the error, though?

**Comment by monacofj** [comment]
@matheushjs, it happens if you download the tarball (not from CVS), build, install and try to run from the ~project-tree (not installed)~ install path.

It seems an issue with `Makefile.am`. I'll check it out.

**Comment by matheushjs** [comment]
@monacofj  Ok, I see what you mean. Yeah I can reproduce that problem.

However, for @zanuttin , I think he was having problems even after installing. For him, I think the solution is to install with sudo permissions.

Incidentally, I think we should update the README to state that `make install` is to be made with sudo...

**Comment by monacofj** [comment]
Sure, @matheushjs, I'll update `README` as well.

**Comment by monacofj** [comment]
@zanuttin, can you still reproduce this with 0.1.0-alpha?
I can no longer reproduce the bug and cannot figure out what I did different.
Would you please once more go through the steps to cause the crash?

**Comment by joao-zanutto** [comment]
Sorry for the delay. As @matheushjs said, installing with `sudo` is a solution. I'll try to unistall and reproduce later and post the results.

**Comment by monacofj** [comment]
@zanuttin, no prob.
Would you try without sudo? I

**Comment by joao-zanutto** [comment]
@monacofj I just tried out the **0.1.0-alpha+1** version without `sudo` and got the issue in the screenshot. The steps I to reproduce are:

1. Download and extract latest build
2. Run `./configure` inside the newly extracted folder
3. Run `sudo make uninstall` - _deleting previous install_
4. Run `make` and then `make install`
`
![image](https://user-images.githubusercontent.com/11475695/108162872-c1ae5880-70cc-11eb-815b-6354ca41e56a.png)

**Comment by monacofj** [comment]
Project ended.
