### ISSUE TITLE
Cropped top border

### ISSUE THREAD

**Issue by joao-zanutto** [courselab/ttsnake#80]
**Environment:** Ubuntu 20.10
**Terminal:** zsh
**Screen Resolution:** 1366x768 (16:9)

**Steps to reproduce:**
1. Execute the game with the `ttsnake` command

**Expected Result:**
> Game top border should be displayed in any screen size

**Actual Result:**
> The game top border is cropped out

**Evidences**

![image](https://user-images.githubusercontent.com/11475695/107069999-79846180-67c1-11eb-80aa-b143af4a878e.png)

**Comment by monacofj** [comment]
This probaly dependente on the user's terminal size, but inconvenient.  

Auto resizing would be a intereting.

Meanwhile, shrinking the bottom.menu might help a little.

**Comment by matheushjs** [comment]
I will try to fix this. Since we adopted the POSIX standard, it shouldn't be hard to find the size of the terminal.
