### ISSUE TITLE
Commit disappeared

### ISSUE THREAD

**Issue by matheushjs** [courselab/ttsnake#81]
Commit c91c805a8c649d3aaa0b7cfb722b8c232412c382 disappeared from branches `develop` and `release-0.1.0`.

See the message on top of https://github.com/courselab/ttsnake/commit/c91c805a8c649d3aaa0b7cfb722b8c232412c382

> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

This usually happens when doing `git push --force` or `git reset --hard`. I can't think of other reasons why a commit would disappear.

I can't fix #80 with how things are.

Also, the game is stupidly hard at present, since you only get 10 energy per bite.

**Comment by monacofj** [comment]
@matheushjs, blame me.

I must have done something wrong while merging (thought I had solved, but it seems I haven't).
Do you believe we can work it out?

**Comment by matheushjs** [comment]
@monacofj Depending on what you did, the commits might be in your local git tree, maybe? I was worried that other commits might have disappeared too.

I will reimplement commit c91c805 anyway, so I can fix this issue

**Comment by monacofj** [comment]
@matheushjs, I'm really sorry I messed up :disappointed:

**Comment by matheushjs** [comment]
Don't worry lol it happens
