### ISSUE TITLE
Help & Settings didn't work after You Are Dead

### ISSUE THREAD

**Issue by baldissin** [courselab/ttsnake#82]
**Environment:** Ubuntu 20.10

**Steps to reproduce:**

Press 'h' after dying in the game

**Expected Result:** The settings screen should be displayed.

**Current Result:** The menu is hidden and the user stays on the "You are dead" screen. The button 'r' doesn't work and you only play again if you press 'p'.

**Evidence:**
![image](https://user-images.githubusercontent.com/21284291/107135381-eb9b9a00-68d8-11eb-92de-b6f31084e19d.png)

**Comment by matheushjs** [comment]
Nicely spotted. Fixing it on #84
